version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "${DATADIR}/proxy/certs:/etc/nginx/certs:ro"
    restart: always
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "${DATADIR}/proxy/templates/nginx-compose.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DATADIR}/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    dns: 1.1.1.1
    restart: always

  redis:
    container_name: redis
    image: redis
    expose:
     - "6379/tcp"
    volumes:
      - "${DATADIR}/redis:/data"
    restart: always
    networks:
     - proxy-tier

  db:
    container_name: db
    image: mariadb
    expose:
     - "3306/tcp"
    environment:
     - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
     - "MYSQL_DATABASE=${MYSQL_DATABASE}"
     - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
     - "MYSQL_USER=${MYSQL_USER}"
     - CREATE_DATABASE=true
    command: ["--max-connections", "1000"]
    volumes:
     - "${DATADIR}/mysql:/var/lib/mysql"
    restart: always
    domainname: ${DOMAIN_NAME}
    networks:
     - proxy-tier

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    expose:
     - "80/tcp"
    environment:
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - TRUSTED_DOMAIN1=nextcloud
     - "TRUSTED_DOMAIN2=${SERVER_NAME}"
     - "EXTERNAL_DOMAIN=${SERVER_NAME}"
     - "OVERWRITE_HOST=${SERVER_NAME}"
     - "VIRTUAL_HOST=${SERVER_NAME}"
     - "LETSENCRYPT_HOST=${SERVER_NAME}"
     - "LETSENCRYPT_EMAIL=${EMAIL}"
    networks:
     - proxy-tier
    volumes:
     - "${DATADIR}/custom_apps:/var/www/html/custom_apps"
     - "${DATADIR}/config:/var/www/html/config"
     - "${DATADIR}/data:/var/www/html/data"
    restart: always
    domainname: "${DOMAIN_NAME}"
    depends_on:
     - db
    links:
     - db


networks:
  proxy-tier:
    external:
      name: nginx-proxy
